Algoritmo "fatorial"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Arthur Henrique Kronbauer 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2026
Var
// Seção de Declarações das variáveis 
   numero : inteiro
   fatorial: inteiro
   a : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe um número inteiro: ")
   leia(numero)
   fatorial <- 1
   
   para a de 1 ate numero faca
        fatorial <- fatorial * a
   fimpara
   
   escreval(fatorial)

Fimalgoritmo